apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: isdialogmotepdfgen
  namespace: teamsykefravr
  labels:
    team: teamsykefravr
spec:
  image: {{ image }}
  port: 8080
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 70
  liveness:
    path: /internal/is_alive
    timeout: 1
    initialDelay: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /internal/is_ready
    timeout: 1
    initialDelay: 5
    periodSeconds: 5
    failureThreshold: 30
  leaderElection: false
  prometheus:
    enabled: true
    path: /prometheus
  resources:
    limits:
      memory: 1024Mi
    requests:
      cpu: 100m
      memory: 128Mi
  accessPolicy:
    inbound:
      rules:
        - application: isdialogmote
